require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DealsdirectnavbarsController do

  # This should return the minimal set of attributes required to create a valid
  # Dealsdirectnavbar. As you add validations to Dealsdirectnavbar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sub1" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DealsdirectnavbarsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dealsdirectnavbars as @dealsdirectnavbars" do
      dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dealsdirectnavbars).should eq([dealsdirectnavbar])
    end
  end

  describe "GET show" do
    it "assigns the requested dealsdirectnavbar as @dealsdirectnavbar" do
      dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
      get :show, {:id => dealsdirectnavbar.to_param}, valid_session
      assigns(:dealsdirectnavbar).should eq(dealsdirectnavbar)
    end
  end

  describe "GET new" do
    it "assigns a new dealsdirectnavbar as @dealsdirectnavbar" do
      get :new, {}, valid_session
      assigns(:dealsdirectnavbar).should be_a_new(Dealsdirectnavbar)
    end
  end

  describe "GET edit" do
    it "assigns the requested dealsdirectnavbar as @dealsdirectnavbar" do
      dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
      get :edit, {:id => dealsdirectnavbar.to_param}, valid_session
      assigns(:dealsdirectnavbar).should eq(dealsdirectnavbar)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dealsdirectnavbar" do
        expect {
          post :create, {:dealsdirectnavbar => valid_attributes}, valid_session
        }.to change(Dealsdirectnavbar, :count).by(1)
      end

      it "assigns a newly created dealsdirectnavbar as @dealsdirectnavbar" do
        post :create, {:dealsdirectnavbar => valid_attributes}, valid_session
        assigns(:dealsdirectnavbar).should be_a(Dealsdirectnavbar)
        assigns(:dealsdirectnavbar).should be_persisted
      end

      it "redirects to the created dealsdirectnavbar" do
        post :create, {:dealsdirectnavbar => valid_attributes}, valid_session
        response.should redirect_to(Dealsdirectnavbar.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dealsdirectnavbar as @dealsdirectnavbar" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectnavbar.any_instance.stub(:save).and_return(false)
        post :create, {:dealsdirectnavbar => { "sub1" => "invalid value" }}, valid_session
        assigns(:dealsdirectnavbar).should be_a_new(Dealsdirectnavbar)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectnavbar.any_instance.stub(:save).and_return(false)
        post :create, {:dealsdirectnavbar => { "sub1" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dealsdirectnavbar" do
        dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
        # Assuming there are no other dealsdirectnavbars in the database, this
        # specifies that the Dealsdirectnavbar created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dealsdirectnavbar.any_instance.should_receive(:update_attributes).with({ "sub1" => "MyString" })
        put :update, {:id => dealsdirectnavbar.to_param, :dealsdirectnavbar => { "sub1" => "MyString" }}, valid_session
      end

      it "assigns the requested dealsdirectnavbar as @dealsdirectnavbar" do
        dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
        put :update, {:id => dealsdirectnavbar.to_param, :dealsdirectnavbar => valid_attributes}, valid_session
        assigns(:dealsdirectnavbar).should eq(dealsdirectnavbar)
      end

      it "redirects to the dealsdirectnavbar" do
        dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
        put :update, {:id => dealsdirectnavbar.to_param, :dealsdirectnavbar => valid_attributes}, valid_session
        response.should redirect_to(dealsdirectnavbar)
      end
    end

    describe "with invalid params" do
      it "assigns the dealsdirectnavbar as @dealsdirectnavbar" do
        dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectnavbar.any_instance.stub(:save).and_return(false)
        put :update, {:id => dealsdirectnavbar.to_param, :dealsdirectnavbar => { "sub1" => "invalid value" }}, valid_session
        assigns(:dealsdirectnavbar).should eq(dealsdirectnavbar)
      end

      it "re-renders the 'edit' template" do
        dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectnavbar.any_instance.stub(:save).and_return(false)
        put :update, {:id => dealsdirectnavbar.to_param, :dealsdirectnavbar => { "sub1" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dealsdirectnavbar" do
      dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
      expect {
        delete :destroy, {:id => dealsdirectnavbar.to_param}, valid_session
      }.to change(Dealsdirectnavbar, :count).by(-1)
    end

    it "redirects to the dealsdirectnavbars list" do
      dealsdirectnavbar = Dealsdirectnavbar.create! valid_attributes
      delete :destroy, {:id => dealsdirectnavbar.to_param}, valid_session
      response.should redirect_to(dealsdirectnavbars_url)
    end
  end

end
