require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DealsdirectcategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Dealsdirectcategory. As you add validations to Dealsdirectcategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DealsdirectcategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dealsdirectcategories as @dealsdirectcategories" do
      dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dealsdirectcategories).should eq([dealsdirectcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested dealsdirectcategory as @dealsdirectcategory" do
      dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
      get :show, {:id => dealsdirectcategory.to_param}, valid_session
      assigns(:dealsdirectcategory).should eq(dealsdirectcategory)
    end
  end

  describe "GET new" do
    it "assigns a new dealsdirectcategory as @dealsdirectcategory" do
      get :new, {}, valid_session
      assigns(:dealsdirectcategory).should be_a_new(Dealsdirectcategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested dealsdirectcategory as @dealsdirectcategory" do
      dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
      get :edit, {:id => dealsdirectcategory.to_param}, valid_session
      assigns(:dealsdirectcategory).should eq(dealsdirectcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dealsdirectcategory" do
        expect {
          post :create, {:dealsdirectcategory => valid_attributes}, valid_session
        }.to change(Dealsdirectcategory, :count).by(1)
      end

      it "assigns a newly created dealsdirectcategory as @dealsdirectcategory" do
        post :create, {:dealsdirectcategory => valid_attributes}, valid_session
        assigns(:dealsdirectcategory).should be_a(Dealsdirectcategory)
        assigns(:dealsdirectcategory).should be_persisted
      end

      it "redirects to the created dealsdirectcategory" do
        post :create, {:dealsdirectcategory => valid_attributes}, valid_session
        response.should redirect_to(Dealsdirectcategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dealsdirectcategory as @dealsdirectcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectcategory.any_instance.stub(:save).and_return(false)
        post :create, {:dealsdirectcategory => { "title" => "invalid value" }}, valid_session
        assigns(:dealsdirectcategory).should be_a_new(Dealsdirectcategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectcategory.any_instance.stub(:save).and_return(false)
        post :create, {:dealsdirectcategory => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dealsdirectcategory" do
        dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
        # Assuming there are no other dealsdirectcategories in the database, this
        # specifies that the Dealsdirectcategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dealsdirectcategory.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => dealsdirectcategory.to_param, :dealsdirectcategory => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested dealsdirectcategory as @dealsdirectcategory" do
        dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
        put :update, {:id => dealsdirectcategory.to_param, :dealsdirectcategory => valid_attributes}, valid_session
        assigns(:dealsdirectcategory).should eq(dealsdirectcategory)
      end

      it "redirects to the dealsdirectcategory" do
        dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
        put :update, {:id => dealsdirectcategory.to_param, :dealsdirectcategory => valid_attributes}, valid_session
        response.should redirect_to(dealsdirectcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the dealsdirectcategory as @dealsdirectcategory" do
        dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => dealsdirectcategory.to_param, :dealsdirectcategory => { "title" => "invalid value" }}, valid_session
        assigns(:dealsdirectcategory).should eq(dealsdirectcategory)
      end

      it "re-renders the 'edit' template" do
        dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dealsdirectcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => dealsdirectcategory.to_param, :dealsdirectcategory => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dealsdirectcategory" do
      dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
      expect {
        delete :destroy, {:id => dealsdirectcategory.to_param}, valid_session
      }.to change(Dealsdirectcategory, :count).by(-1)
    end

    it "redirects to the dealsdirectcategories list" do
      dealsdirectcategory = Dealsdirectcategory.create! valid_attributes
      delete :destroy, {:id => dealsdirectcategory.to_param}, valid_session
      response.should redirect_to(dealsdirectcategories_url)
    end
  end

end
