require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoogleplaysController do

  # This should return the minimal set of attributes required to create a valid
  # Googleplay. As you add validations to Googleplay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoogleplaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all googleplays as @googleplays" do
      googleplay = Googleplay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:googleplays).should eq([googleplay])
    end
  end

  describe "GET show" do
    it "assigns the requested googleplay as @googleplay" do
      googleplay = Googleplay.create! valid_attributes
      get :show, {:id => googleplay.to_param}, valid_session
      assigns(:googleplay).should eq(googleplay)
    end
  end

  describe "GET new" do
    it "assigns a new googleplay as @googleplay" do
      get :new, {}, valid_session
      assigns(:googleplay).should be_a_new(Googleplay)
    end
  end

  describe "GET edit" do
    it "assigns the requested googleplay as @googleplay" do
      googleplay = Googleplay.create! valid_attributes
      get :edit, {:id => googleplay.to_param}, valid_session
      assigns(:googleplay).should eq(googleplay)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Googleplay" do
        expect {
          post :create, {:googleplay => valid_attributes}, valid_session
        }.to change(Googleplay, :count).by(1)
      end

      it "assigns a newly created googleplay as @googleplay" do
        post :create, {:googleplay => valid_attributes}, valid_session
        assigns(:googleplay).should be_a(Googleplay)
        assigns(:googleplay).should be_persisted
      end

      it "redirects to the created googleplay" do
        post :create, {:googleplay => valid_attributes}, valid_session
        response.should redirect_to(Googleplay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved googleplay as @googleplay" do
        # Trigger the behavior that occurs when invalid params are submitted
        Googleplay.any_instance.stub(:save).and_return(false)
        post :create, {:googleplay => { "url" => "invalid value" }}, valid_session
        assigns(:googleplay).should be_a_new(Googleplay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Googleplay.any_instance.stub(:save).and_return(false)
        post :create, {:googleplay => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested googleplay" do
        googleplay = Googleplay.create! valid_attributes
        # Assuming there are no other googleplays in the database, this
        # specifies that the Googleplay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Googleplay.any_instance.should_receive(:update_attributes).with({ "url" => "MyString" })
        put :update, {:id => googleplay.to_param, :googleplay => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested googleplay as @googleplay" do
        googleplay = Googleplay.create! valid_attributes
        put :update, {:id => googleplay.to_param, :googleplay => valid_attributes}, valid_session
        assigns(:googleplay).should eq(googleplay)
      end

      it "redirects to the googleplay" do
        googleplay = Googleplay.create! valid_attributes
        put :update, {:id => googleplay.to_param, :googleplay => valid_attributes}, valid_session
        response.should redirect_to(googleplay)
      end
    end

    describe "with invalid params" do
      it "assigns the googleplay as @googleplay" do
        googleplay = Googleplay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Googleplay.any_instance.stub(:save).and_return(false)
        put :update, {:id => googleplay.to_param, :googleplay => { "url" => "invalid value" }}, valid_session
        assigns(:googleplay).should eq(googleplay)
      end

      it "re-renders the 'edit' template" do
        googleplay = Googleplay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Googleplay.any_instance.stub(:save).and_return(false)
        put :update, {:id => googleplay.to_param, :googleplay => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested googleplay" do
      googleplay = Googleplay.create! valid_attributes
      expect {
        delete :destroy, {:id => googleplay.to_param}, valid_session
      }.to change(Googleplay, :count).by(-1)
    end

    it "redirects to the googleplays list" do
      googleplay = Googleplay.create! valid_attributes
      delete :destroy, {:id => googleplay.to_param}, valid_session
      response.should redirect_to(googleplays_url)
    end
  end

end
