require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HarajsHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # HarajsHistory. As you add validations to HarajsHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HarajsHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all harajs_histories as @harajs_histories" do
      harajs_history = HarajsHistory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:harajs_histories).should eq([harajs_history])
    end
  end

  describe "GET show" do
    it "assigns the requested harajs_history as @harajs_history" do
      harajs_history = HarajsHistory.create! valid_attributes
      get :show, {:id => harajs_history.to_param}, valid_session
      assigns(:harajs_history).should eq(harajs_history)
    end
  end

  describe "GET new" do
    it "assigns a new harajs_history as @harajs_history" do
      get :new, {}, valid_session
      assigns(:harajs_history).should be_a_new(HarajsHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested harajs_history as @harajs_history" do
      harajs_history = HarajsHistory.create! valid_attributes
      get :edit, {:id => harajs_history.to_param}, valid_session
      assigns(:harajs_history).should eq(harajs_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HarajsHistory" do
        expect {
          post :create, {:harajs_history => valid_attributes}, valid_session
        }.to change(HarajsHistory, :count).by(1)
      end

      it "assigns a newly created harajs_history as @harajs_history" do
        post :create, {:harajs_history => valid_attributes}, valid_session
        assigns(:harajs_history).should be_a(HarajsHistory)
        assigns(:harajs_history).should be_persisted
      end

      it "redirects to the created harajs_history" do
        post :create, {:harajs_history => valid_attributes}, valid_session
        response.should redirect_to(HarajsHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved harajs_history as @harajs_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        HarajsHistory.any_instance.stub(:save).and_return(false)
        post :create, {:harajs_history => { "url" => "invalid value" }}, valid_session
        assigns(:harajs_history).should be_a_new(HarajsHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HarajsHistory.any_instance.stub(:save).and_return(false)
        post :create, {:harajs_history => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested harajs_history" do
        harajs_history = HarajsHistory.create! valid_attributes
        # Assuming there are no other harajs_histories in the database, this
        # specifies that the HarajsHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HarajsHistory.any_instance.should_receive(:update_attributes).with({ "url" => "MyString" })
        put :update, {:id => harajs_history.to_param, :harajs_history => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested harajs_history as @harajs_history" do
        harajs_history = HarajsHistory.create! valid_attributes
        put :update, {:id => harajs_history.to_param, :harajs_history => valid_attributes}, valid_session
        assigns(:harajs_history).should eq(harajs_history)
      end

      it "redirects to the harajs_history" do
        harajs_history = HarajsHistory.create! valid_attributes
        put :update, {:id => harajs_history.to_param, :harajs_history => valid_attributes}, valid_session
        response.should redirect_to(harajs_history)
      end
    end

    describe "with invalid params" do
      it "assigns the harajs_history as @harajs_history" do
        harajs_history = HarajsHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HarajsHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => harajs_history.to_param, :harajs_history => { "url" => "invalid value" }}, valid_session
        assigns(:harajs_history).should eq(harajs_history)
      end

      it "re-renders the 'edit' template" do
        harajs_history = HarajsHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HarajsHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => harajs_history.to_param, :harajs_history => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested harajs_history" do
      harajs_history = HarajsHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => harajs_history.to_param}, valid_session
      }.to change(HarajsHistory, :count).by(-1)
    end

    it "redirects to the harajs_histories list" do
      harajs_history = HarajsHistory.create! valid_attributes
      delete :destroy, {:id => harajs_history.to_param}, valid_session
      response.should redirect_to(harajs_histories_url)
    end
  end

end
