require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HarajsController do

  # This should return the minimal set of attributes required to create a valid
  # Haraj. As you add validations to Haraj, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HarajsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all harajs as @harajs" do
      haraj = Haraj.create! valid_attributes
      get :index, {}, valid_session
      assigns(:harajs).should eq([haraj])
    end
  end

  describe "GET show" do
    it "assigns the requested haraj as @haraj" do
      haraj = Haraj.create! valid_attributes
      get :show, {:id => haraj.to_param}, valid_session
      assigns(:haraj).should eq(haraj)
    end
  end

  describe "GET new" do
    it "assigns a new haraj as @haraj" do
      get :new, {}, valid_session
      assigns(:haraj).should be_a_new(Haraj)
    end
  end

  describe "GET edit" do
    it "assigns the requested haraj as @haraj" do
      haraj = Haraj.create! valid_attributes
      get :edit, {:id => haraj.to_param}, valid_session
      assigns(:haraj).should eq(haraj)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Haraj" do
        expect {
          post :create, {:haraj => valid_attributes}, valid_session
        }.to change(Haraj, :count).by(1)
      end

      it "assigns a newly created haraj as @haraj" do
        post :create, {:haraj => valid_attributes}, valid_session
        assigns(:haraj).should be_a(Haraj)
        assigns(:haraj).should be_persisted
      end

      it "redirects to the created haraj" do
        post :create, {:haraj => valid_attributes}, valid_session
        response.should redirect_to(Haraj.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved haraj as @haraj" do
        # Trigger the behavior that occurs when invalid params are submitted
        Haraj.any_instance.stub(:save).and_return(false)
        post :create, {:haraj => { "title" => "invalid value" }}, valid_session
        assigns(:haraj).should be_a_new(Haraj)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Haraj.any_instance.stub(:save).and_return(false)
        post :create, {:haraj => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested haraj" do
        haraj = Haraj.create! valid_attributes
        # Assuming there are no other harajs in the database, this
        # specifies that the Haraj created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Haraj.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => haraj.to_param, :haraj => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested haraj as @haraj" do
        haraj = Haraj.create! valid_attributes
        put :update, {:id => haraj.to_param, :haraj => valid_attributes}, valid_session
        assigns(:haraj).should eq(haraj)
      end

      it "redirects to the haraj" do
        haraj = Haraj.create! valid_attributes
        put :update, {:id => haraj.to_param, :haraj => valid_attributes}, valid_session
        response.should redirect_to(haraj)
      end
    end

    describe "with invalid params" do
      it "assigns the haraj as @haraj" do
        haraj = Haraj.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Haraj.any_instance.stub(:save).and_return(false)
        put :update, {:id => haraj.to_param, :haraj => { "title" => "invalid value" }}, valid_session
        assigns(:haraj).should eq(haraj)
      end

      it "re-renders the 'edit' template" do
        haraj = Haraj.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Haraj.any_instance.stub(:save).and_return(false)
        put :update, {:id => haraj.to_param, :haraj => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested haraj" do
      haraj = Haraj.create! valid_attributes
      expect {
        delete :destroy, {:id => haraj.to_param}, valid_session
      }.to change(Haraj, :count).by(-1)
    end

    it "redirects to the harajs list" do
      haraj = Haraj.create! valid_attributes
      delete :destroy, {:id => haraj.to_param}, valid_session
      response.should redirect_to(harajs_url)
    end
  end

end
