require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItunesController do

  # This should return the minimal set of attributes required to create a valid
  # Itune. As you add validations to Itune, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "guid" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItunesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all itunes as @itunes" do
      itune = Itune.create! valid_attributes
      get :index, {}, valid_session
      assigns(:itunes).should eq([itune])
    end
  end

  describe "GET show" do
    it "assigns the requested itune as @itune" do
      itune = Itune.create! valid_attributes
      get :show, {:id => itune.to_param}, valid_session
      assigns(:itune).should eq(itune)
    end
  end

  describe "GET new" do
    it "assigns a new itune as @itune" do
      get :new, {}, valid_session
      assigns(:itune).should be_a_new(Itune)
    end
  end

  describe "GET edit" do
    it "assigns the requested itune as @itune" do
      itune = Itune.create! valid_attributes
      get :edit, {:id => itune.to_param}, valid_session
      assigns(:itune).should eq(itune)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Itune" do
        expect {
          post :create, {:itune => valid_attributes}, valid_session
        }.to change(Itune, :count).by(1)
      end

      it "assigns a newly created itune as @itune" do
        post :create, {:itune => valid_attributes}, valid_session
        assigns(:itune).should be_a(Itune)
        assigns(:itune).should be_persisted
      end

      it "redirects to the created itune" do
        post :create, {:itune => valid_attributes}, valid_session
        response.should redirect_to(Itune.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved itune as @itune" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itune.any_instance.stub(:save).and_return(false)
        post :create, {:itune => { "guid" => "invalid value" }}, valid_session
        assigns(:itune).should be_a_new(Itune)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Itune.any_instance.stub(:save).and_return(false)
        post :create, {:itune => { "guid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested itune" do
        itune = Itune.create! valid_attributes
        # Assuming there are no other itunes in the database, this
        # specifies that the Itune created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Itune.any_instance.should_receive(:update_attributes).with({ "guid" => "MyString" })
        put :update, {:id => itune.to_param, :itune => { "guid" => "MyString" }}, valid_session
      end

      it "assigns the requested itune as @itune" do
        itune = Itune.create! valid_attributes
        put :update, {:id => itune.to_param, :itune => valid_attributes}, valid_session
        assigns(:itune).should eq(itune)
      end

      it "redirects to the itune" do
        itune = Itune.create! valid_attributes
        put :update, {:id => itune.to_param, :itune => valid_attributes}, valid_session
        response.should redirect_to(itune)
      end
    end

    describe "with invalid params" do
      it "assigns the itune as @itune" do
        itune = Itune.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itune.any_instance.stub(:save).and_return(false)
        put :update, {:id => itune.to_param, :itune => { "guid" => "invalid value" }}, valid_session
        assigns(:itune).should eq(itune)
      end

      it "re-renders the 'edit' template" do
        itune = Itune.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Itune.any_instance.stub(:save).and_return(false)
        put :update, {:id => itune.to_param, :itune => { "guid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested itune" do
      itune = Itune.create! valid_attributes
      expect {
        delete :destroy, {:id => itune.to_param}, valid_session
      }.to change(Itune, :count).by(-1)
    end

    it "redirects to the itunes list" do
      itune = Itune.create! valid_attributes
      delete :destroy, {:id => itune.to_param}, valid_session
      response.should redirect_to(itunes_url)
    end
  end

end
