require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VpnsController do

  # This should return the minimal set of attributes required to create a valid
  # Vpn. As you add validations to Vpn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VpnsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vpns as @vpns" do
      vpn = Vpn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vpns).should eq([vpn])
    end
  end

  describe "GET show" do
    it "assigns the requested vpn as @vpn" do
      vpn = Vpn.create! valid_attributes
      get :show, {:id => vpn.to_param}, valid_session
      assigns(:vpn).should eq(vpn)
    end
  end

  describe "GET new" do
    it "assigns a new vpn as @vpn" do
      get :new, {}, valid_session
      assigns(:vpn).should be_a_new(Vpn)
    end
  end

  describe "GET edit" do
    it "assigns the requested vpn as @vpn" do
      vpn = Vpn.create! valid_attributes
      get :edit, {:id => vpn.to_param}, valid_session
      assigns(:vpn).should eq(vpn)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vpn" do
        expect {
          post :create, {:vpn => valid_attributes}, valid_session
        }.to change(Vpn, :count).by(1)
      end

      it "assigns a newly created vpn as @vpn" do
        post :create, {:vpn => valid_attributes}, valid_session
        assigns(:vpn).should be_a(Vpn)
        assigns(:vpn).should be_persisted
      end

      it "redirects to the created vpn" do
        post :create, {:vpn => valid_attributes}, valid_session
        response.should redirect_to(Vpn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vpn as @vpn" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vpn.any_instance.stub(:save).and_return(false)
        post :create, {:vpn => { "name" => "invalid value" }}, valid_session
        assigns(:vpn).should be_a_new(Vpn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vpn.any_instance.stub(:save).and_return(false)
        post :create, {:vpn => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vpn" do
        vpn = Vpn.create! valid_attributes
        # Assuming there are no other vpns in the database, this
        # specifies that the Vpn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vpn.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => vpn.to_param, :vpn => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested vpn as @vpn" do
        vpn = Vpn.create! valid_attributes
        put :update, {:id => vpn.to_param, :vpn => valid_attributes}, valid_session
        assigns(:vpn).should eq(vpn)
      end

      it "redirects to the vpn" do
        vpn = Vpn.create! valid_attributes
        put :update, {:id => vpn.to_param, :vpn => valid_attributes}, valid_session
        response.should redirect_to(vpn)
      end
    end

    describe "with invalid params" do
      it "assigns the vpn as @vpn" do
        vpn = Vpn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vpn.any_instance.stub(:save).and_return(false)
        put :update, {:id => vpn.to_param, :vpn => { "name" => "invalid value" }}, valid_session
        assigns(:vpn).should eq(vpn)
      end

      it "re-renders the 'edit' template" do
        vpn = Vpn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vpn.any_instance.stub(:save).and_return(false)
        put :update, {:id => vpn.to_param, :vpn => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vpn" do
      vpn = Vpn.create! valid_attributes
      expect {
        delete :destroy, {:id => vpn.to_param}, valid_session
      }.to change(Vpn, :count).by(-1)
    end

    it "redirects to the vpns list" do
      vpn = Vpn.create! valid_attributes
      delete :destroy, {:id => vpn.to_param}, valid_session
      response.should redirect_to(vpns_url)
    end
  end

end
